### ISSUE TITLE
1.86 release

### ISSUE THREAD

**Issue by gaul** [s3fs-fuse/s3fs-fuse#1050]
master has a number of [changes since 1.85](https://github.com/s3fs-fuse/s3fs-fuse/compare/v1.85...master), some in-progress pull requests, and a few issues that I am investigating:

- [x] Time problem with large files #1019 (regression from 1.84)
- [x] file corruption with `use_cache` and external modifications #1047 
- [x] `git clone` premature end of pack file #839
- [x] The upload element blocking subsequent transfers #928

**Comment by amolthorat1** [comment]
Hello,

Any update on the next release date for s3fs?

Thanks.

**Comment by ggtakec** [comment]
@amolthorat1 I want to add # 1098 in addition to the contents suggested by @gaul.
Since some correspondence still remains now, please wait a little more.

**Comment by gaul** [comment]
You do not need to wait for a release version; just `git clone` the repository to get the latest fixes.

**Comment by amolthorat1** [comment]
We need to be able to point customer to a release version - getting the source code and building it may not work for them.

**Comment by gaul** [comment]
s3fs will release when it is ready.  I suggest you fork the repo and tag a version for your customer.

**Comment by gaul** [comment]
@ggtakec Fedora 31 and Ubuntu 19.10 both release in October and it would be nice if they could include the many bug fixes since 1.85.  Could we merge #1066 and #1107 and tag 1.86?  I worry that delaying the release for #1098 to mature poses too much risk.  I can handle the release process if this helps.

**Comment by gaul** [comment]
@ggtakec I would like to release 1.86 in the hope that Ubuntu 20.04 LTS can include it.  Would you mind if I tagged the current master and wrote the release notes?  For the latter I would like to follow a simpler, user-focused format since GitHub already provides the commit list between versions.  I drafted this:

* add intelligent_ia storage tier
* add requester_pays support
* add session token support
* add symlink cache
* allow concurrent metadata queries during data operations
* allow large files on 32-bit systems like Raspberry Pi
* allow SSE-C keys to have NUL bytes
* enable various optimizations when using modern curl
* fix clock skew errors when writing large files
* fix data corruption when external modification changes a cached object
* fix data corruption when opening a second fd to an unflushed file
* fix multiple concurrency issues
* use server-side copy for partially modified files

**Comment by ggtakec** [comment]
@gaul I suppose that your description is okay, but ChangeLog and ReleaseNotes should match the old ChangeLog format.
```
#<PR ID> <Title>
```
I think that you can add your description(text) to Release tag page as outline.

However, I would like to complete #1151 if possible.
We believe that only the test results in an error, so we can handle it.
I want to investigate the cause as soon as possible.

Sorry to keep you waiting

**Comment by gaul** [comment]
Agreed that linking to the PRs is a good idea.  However, I have concerns about waiting for one more PR.  I would really like Ubuntu 20.04 to include s3fs 1.86 since it has several data corruption fixes.  This release is LTS which will be supported for 5 years likely without s3fs upgrades:

https://wiki.ubuntu.com/FocalFossa/ReleaseSchedule

I don't know if it is too late to include it already but Ubuntu recently upgraded to 1.85:

https://bugs.launchpad.net/ubuntu/+source/s3fs-fuse/+bug/1828849

**Comment by ggtakec** [comment]
@gaul 
I will add #1151's comment, but it seems that this PR will take time to resolve.
(I merged one PR as #1230 for fixing test code.)
It seems that several factors are compounded.
I agree that #1151 will carry over to the next version.
(I will continue to investigate)

We are going to release v1.86 with the current code.

**Comment by ggtakec** [comment]
@gaul I merged #1232. 
I think this will make the #1151 PR a success.

**Comment by gaul** [comment]
I plan to tag the release this week.  I am still scrubbing through all the bugs but surfaced a few minor PRs.

**Comment by ggtakec** [comment]
@gaul I understand the release tag.
What about the target date and time for assigning release tags around Feb 9?
By then, I think I'll raise the PR for minor fixes (no logic changes).

**Comment by gaul** [comment]
Sorry I already tagged this and requested that Ubuntu upgrade to 1.86:

https://bugs.launchpad.net/ubuntu/+source/s3fs-fuse/+bug/1862023

**Comment by juliogonzalez** [comment]
Starting submissions for openSUSE (devel project), Fedora and CentOS.

**Comment by juliogonzalez** [comment]
For reference:

OpenSUSE: https://build.opensuse.org/request/show/770406
Fedora Rawhide & 32 (koji build): https://koji.fedoraproject.org/koji/taskinfo?taskID=41399105
EPEL8: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-3d094c3f20
EPEL7: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-d4cebca350
Fedora31: https://bodhi.fedoraproject.org/updates/FEDORA-2020-d183c526b4
Fedora30: https://bodhi.fedoraproject.org/updates/FEDORA-2020-8d0d2ef18c

**Comment by gaul** [comment]
@juliogonzalez Thanks for packaging this!  I submitted positive karma for Fedora 31.  Personally Fedora 30 does not interest me but I am glad that EPEL 7 and 8 will include s3fs 1.86 since these will live on for many years.  Ideally users would report bugs here since I rarely check distribution issue trackers but I understand that their policies.
